### ISSUE TITLE
[Feat] 인트로 게임 다른 뷰와 연결

### ISSUE THREAD

**Issue by Kiyoung-Kim-57** [DeveloperAcademy-POSTECH/MC3-Team16-QAQA#68]
## 🛠 Issue
인트로 게임 시작전 카운트 다운 및 다른 뷰와 연결

## 📝 To-do

- [ ] 321 카운트 다운뷰 추가
- [ ] 게임 시작 전 안내 보달과 연동
- [ ] 게임 끝난 후 IntroResultView와 연결
